### ISSUE TITLE
Disconnects after a few seconds

### ISSUE THREAD

**Issue by rs1990** [roboTJ101/ros_myo#9]
Hello,

i got the myo to start working and it ran brilliantly , but after just a few seconds it suddenly stops and i get the below response. Any help please ?

````
scan response: Packet(80, 06, 00, [C7 00 12 C4 16 9A 3A FA 00 FF 1F 09 08 4D 79 6F 00 00 00 00 00 02 01 06 11 06 42 48 12 4A 7F 2C 48 47 B9 DE 04 A9 01 00 06 D5])
firmware version: 1.5.1970.2
device name: Myo

Disconnecting...

Traceback (most recent call last):
  File "/home/swapnil/catkin_ws/src/ros_myo/scripts/myo-rawNode.py", line 444, in <module>
    m.run(1)
  File "/home/swapnil/catkin_ws/src/ros_myo/scripts/myo-rawNode.py", line 204, in run
    self.bt.recv_packet(timeout)
  File "/home/swapnil/catkin_ws/src/ros_myo/scripts/myo-rawNode.py", line 87, in recv_packet
    self.handle_event(ret)
  File "/home/swapnil/catkin_ws/src/ros_myo/scripts/myo-rawNode.py", line 120, in handle_event
    h(p)
  File "/home/swapnil/catkin_ws/src/ros_myo/scripts/myo-rawNode.py", line 300, in handle_data
    typ, val, xdir = unpack('3B', pay)
  File "/home/swapnil/catkin_ws/src/ros_myo/scripts/common.py", line 7, in unpack
    return struct.unpack('<' + fmt, *args)
struct.error: unpack requires a string argument of length 3
````

**Comment by j5207** [comment]
same issue here. It would be much helpful if anyone could answer
